### ISSUE TITLE
Plugin with Qt 5.8.

### ISSUE THREAD

**Issue by aospiridonov** [ssbssa/heob#14]
Dear Hannes Domani,

I can not configure to be used in Qt Creator analogous
http://doc.qt.io/qtcreator/creator-heob.html

Thanks, Alex

**Comment by ssbssa** [comment]
What Qt Creator version?
What is your actual problem?

**Comment by aospiridonov** [comment]
Qt Creator 4.2.1 (Qt 5.8.0  MSVC 2015)

I don't know how to build from the repository to get the plugin installer. 
(I build with msvs and have heob.exe but I don't know how to integrate with Qt Creator)
I want to get as http://doc.qt.io/qtcreator/creator-heob.html

**Comment by ssbssa** [comment]
heob integration was introduced with [Qt Creator 4.6](https://code.qt.io/cgit/qt-creator/qt-creator.git/plain/dist/changes-4.6.0.md?h=4.6).

**Comment by aospiridonov** [comment]
Thanks.
But,
I started in Qt Creator 4.7.1, it worked and there was a window where it's written to "kill".
I press "k", but no reports (leaks.xml not found).
Is there any manual or an available example?

**Comment by ssbssa** [comment]
The "kill" text should only be visible short on startup of the program, you shouldn't actually press it, only if something is wrong.

Some antivirus software interfere with heob, maybe that's what's happening here.

**Comment by ssbssa** [comment]
Were you able to make it work?

**Comment by aospiridonov** [comment]
Yes, I was able to run it to work. But it only works for the x64 compiler (msvs 14.0 amd64). In x86 does not work. Put testing for Qt Creator 4.7.1 x86 and x64 version separately. Files heob I download with https://sourceforge.net/projects/heob/files/heob-2.1/

**Comment by ssbssa** [comment]
It should work for x86 as well, have you tried it with disabled antivirus?

**Comment by aospiridonov** [comment]
Files heob32.exe and heob64.exe added to exceptions in antivirus.

**Comment by ssbssa** [comment]
Hmmm, the antivirus software I use still interferes with heob even if it's added as exceptions, it only works if I disable antivirus completely.

**Comment by ssbssa** [comment]
I'm gonna close this now.
If you have any more questions, feel free to reopen.
