### ISSUE TITLE
Starting heob disabled

### ISSUE THREAD

**Issue by calvariomind** [ssbssa/heob#20]
Hello,
Thank you for this great tool. I have been using it for some time and it really helps me to catch those really annoying and hard to find memory bugs.

I would like to know if it is possible to start heob in some type of disabled state, without memory leaks checking, and activate it later during the target application usage. I am using heob from the command prompt and the target application is a c++ visual studio application.

Thanks in advance,
José Calvário

**Comment by ssbssa** [comment]
Do you mean, like e.g., start with disabled memory leak check during GUI startup, and manually enable it just before pressing some button?
That's possible with the option `-k1`, which gives you a very simple console interface (which can be controlled with the keys n/f/c/s).

If you mean something else, please elaborate.

**Comment by calvariomind** [comment]
Yes, that is exactly what I need. Thanks a lot!

**Comment by ssbssa** [comment]
Just for reference, you can additionally enable Global Hotkeys (sometimes useful if the heob console window is in the background) with `-G1`, see `heob64 -HH` for the exact keys.

**Comment by calvariomind** [comment]
Thanks again... that was very useful information.
