### ISSUE TITLE
can't compile heob with mingw

### ISSUE THREAD

**Issue by chachabules** [ssbssa/heob#25]
when I run mingw32-make in the default fold, the console make error and hint "extension if not specified.  A single file name is an input file.No input-file is stdin, default rc.  No output-file is stdout, default rc."
please tell me what is worry with it and how to fix this problem. thank you

**Comment by ssbssa** [comment]
I just tried it now with the mingw32-make version I have, which is version 3.80 from 2002, and it works.
I don't know where I can get a more recent one, since I usually just use make from MSYS2.

Also, please add the full output after you run mingw32-make.

**Comment by chachabules** [comment]
I just tried it with msys2, and works well.Thank you very much, wish a good day
