### ISSUE TITLE
GitHub UI: Reduce noise

### ISSUE THREAD

**Issue by jcfr** [ssbssa/heob#26]
### > Reduce noise

@ssbssa Thanks for putting together this tool :pray: 

To remove the "noise" associated with the project, I suggest disabling the following unused features if it still applies:

| Go to General settings and disable the `Wiki` and `Projects` tabs | If empty or unused, hide `Packages` section on the right side |
|--|--|
| ![GitHub: Projects & Wiki tabs](https://i.imgur.com/nMPUPVQ.png) | ![GitHub: Release & Packages sections](https://i.imgur.com/pf5VGZY.png) |

### Rational

It is just to simplify things.

For example, if user support is provided via a forum then it is better to turn off `Discussions`, so that there is no need to monitor two user support sites, but only one.

If `Releases` and `Packages` are not used, so it is cleaner to hide them (to indicate that it is not the way how we manage releases and packages).

`Projects` feature is rarely used in general and this repository does not use it either. If the user clicks on `Projects` then an empty page is s displayed. It is better to not display the heading at all, to save the extra two clicks for users exploring the project.

Wiki on Github is meant to be a lighter weight tool for documentation. The issue is that it is too limited, for example contributors either can make changes directly (without pull request) or they cannot make changes at all. It also lead to write redundant content, since Github quite nicely renders markdown pages in the main repository. For small projects it is simpler and more consistent to keep all documentation in markdown files in the main repository.

_Co-authored by @lassoan_

---

<sub>_This comment was adapted from my [GitHub saved replies](https://docs.github.com/en/get-started/writing-on-github/working-with-saved-replies/using-saved-replies), it is licensed under a [Creative Commons Attribution 4.0 International License][cc-by-40] and you were welcome to reuse it. [![Creative Commons License][cc-by-40-img]][cc-by-40]_</sub>

[cc-by-40]: http://creativecommons.org/licenses/by/4.0/
[cc-by-40-img]: https://i.creativecommons.org/l/by/4.0/80x15.png

**Comment by ssbssa** [comment]
Done.
