### ISSUE TITLE
Heob: Application stopped unexpectedly.

### ISSUE THREAD

**Issue by MrHulu** [ssbssa/heob#27]
Hello, I also have this problem: - 1: error: Heob: Application stopped unexpectedly.
I don't know what the problem is, I have two projects locally, the small one has no problem, the big one reports an error. I hope you can give me some advice or help. Thank you very much.
The version of heob is 3.1.7, Qt Creator is 8.0.1, Base on Qt6.3.1 (MSVC 2019 x86_64) From revision 9c963ce8ae 
![QQ截图20221212162602](https://user-images.githubusercontent.com/62984804/206997011-dedafd86-cce4-4238-ab72-9894844f27e2.png)
![screenshot-20221212-162549](https://user-images.githubusercontent.com/62984804/206997027-71d76edf-4148-4e9f-9f16-890fd1d262be.png)

**Comment by MrHulu** [comment]
忘了说，我是在我的程序：用户操作界面上点击关闭窗口出现的

**Comment by ssbssa** [comment]
Could you please try the latest development version?
You can get it here: https://ci.appveyor.com/api/projects/ssbssa/heob/artifacts/heob.7z?branch=master

**Comment by MrHulu** [comment]
![image](https://user-images.githubusercontent.com/62984804/209753514-b38a5366-d68b-4358-9e80-f265b15e20c8.png)
Hi, I downloaded the latest version and ran it through this way. When I closed my program, I found that the program did not exit properly. Again task manager can see my program. This makes it impossible to analyse. Why is this?

**Comment by MrHulu** [comment]
![image](https://user-images.githubusercontent.com/62984804/209753811-0ee289f2-6869-4164-a840-d3c7d7ab7f15.png)
If I have used this method to debug my program, it exits and analyses normally. The problem is that this method does not analyse my memory leaks, I need to Detect Leak Type, and then this method does not work properly. It's just too much of a pain in the arse.

**Comment by MrHulu** [comment]
@ssbssa Has this ever happened to you?

**Comment by ssbssa** [comment]
If you use `Detect Leak Types`, it may take a lot of time to analyze, depending on the number of leaks you have.
I implemented this variant before I found out about flame graphs, which I think are a much better way of visualization for leaks.
You can try it out with the extra arguments `-vleaks.svg -g2` (with leak details `Simple`), it should then create a flame graph leaks.svg file which you can open with a browser.

**Comment by MrHulu** [comment]
Thanks, I'll try it later

**Comment by ssbssa** [comment]
I'm closing this now, since there are no open issues any more.
If you have any more problems or questions, feel free to reopen.
