### ISSUE TITLE
Executable remains open after the app is done

### ISSUE THREAD

**Issue by orgads** [ssbssa/heob#4]
The exe file of the debuggee cannot be re-linked until the console window is closed (`APPLICATION EXIT` prompt).

**Comment by ssbssa** [comment]
That is done because I might want to see the final output of a console program.
If you don't need to "control leak recording", disabling it does avoid this behavior.

**Comment by orgads** [comment]
Then maybe use a stub executer like qtc does?

**Comment by ssbssa** [comment]
@orgads Thanks for your input, and for introducing me to git submodules (know about it but never looked into it) and qbs (didn't know about that before at all, but I was actually wondering if something like this existed for Qt Creator).

**Comment by orgads** [comment]
You're welcome. Thanks for this great tool :)
