### ISSUE TITLE
Crash when using heob on Qt 5.11 application

### ISSUE THREAD

**Issue by mitchcurtis** [ssbssa/heob#7]
[heob-crash.zip](https://github.com/ssbssa/heob/files/1883110/heob-crash.zip)

1. Build the attached application with Qt 5.11 (betas are currently available in the online installer).
2. Run it through heob in Qt Creator.
3. Click the "Load" button in the application's window.
4. Hit "Off" then "On" then "Clear".
5. Close the application. Heob should crash. You might need to try steps 2 to 5 a few times before it crashes.

**Comment by ssbssa** [comment]
Interesting, I havn't had heob crashes in quite a while, so I hope i can reproduce once I've downloaded/installed the 5.11 beta.

**Comment by ssbssa** [comment]
Sadly I can't reproduce your crash.
Are you using 32 or 64bit, Debug or Release build?
And is it really heob32/64.exe itself that's crashing, not the heob-crash.exe?

**Comment by mitchcurtis** [comment]
> Sadly I can't reproduce your crash.

Did you try a few times? It didn't crash for me the first two times, but on the third try.

> Are you using 32 or 64bit, Debug or Release build?

64 bit debug build of the application being run under heob. For heob itself I'm using the 64 bit binaries that you have provided.

> And is it really heob32/64.exe itself that's crashing, not the heob-crash.exe?

It says "heap observer has stopped working" in the error message box, and "Heob: Heob stopped unexpectedly." in Creator's issues pane. Other than that, I'm not sure how to check.

**Comment by ssbssa** [comment]
> Did you try a few times? It didn't crash for me the first two times, but on the third try.

Yes, more than 20 times.

> 64 bit debug build of the application being run under heob. For heob itself I'm using the 64 bit binaries that you have provided.

I guess you mean the heob-2.0.7z.

> It says "heap observer has stopped working" in the error message box, and "Heob: Heob stopped unexpectedly." in Creator's issues pane. I am yet to see the application itself crash.

Very weird.
Does it happen with the heob executable you built yourself as well?

**Comment by ssbssa** [comment]
@mitchcurtis
Can you please attach the generated leaks.xml after a crash happened?
It might give me a hint where the problem is.

**Comment by mitchcurtis** [comment]
@ssbssa where is it? I don't see it in the source or build directory, so maybe it wasn't generated on account of the crash?

**Comment by mitchcurtis** [comment]
> Does it happen with the heob executable you built yourself as well?

Yes.

Oh, I was looking in the wrong place. Here's leaks.xml using a self-built heob.
[leaks.zip](https://github.com/ssbssa/heob/files/1901797/leaks.zip)

**Comment by ssbssa** [comment]
> Here's leaks.xml using a self-built heob.

Looks like it crashes before any leak-data is written is written, so sadly this doesn't narrow it down by much.

Have you tried it with a debug build to see where exactly it crashes?

**Comment by ssbssa** [comment]
Thank you, I was finally able to reproduce with this additional information.

I'm thinking of creating a new release because of this fix (and the few feature requests I implemented since the last release).

**Comment by mitchcurtis** [comment]
Good to hear!


+1 for a new release. :)
