### ISSUE TITLE
Can't build .qbs project

### ISSUE THREAD

**Issue by mitchcurtis** [ssbssa/heob#8]
I'm trying to build heob in the hopes that I can get a backtrace for https://github.com/ssbssa/heob/issues/7, but I get a bunch of errors:

> C:\dev\heob\heob.qbs:4: warning: Referenced directory 'C:/dev/heob/dwarfstack/dwarfstack.qbs' does not contain a qbs file.

From the README, it seems that I should be able to build without the dwarfstack stuff (which seems to be a submodule), so I commented it out:

```
diff --git a/heob.qbs b/heob.qbs
index bcd1f67..0bd7fc2 100644
--- a/heob.qbs
+++ b/heob.qbs
@@ -1,7 +1,7 @@
 import qbs

 Project {
-    references: "dwarfstack/dwarfstack.qbs"
+//    references: "dwarfstack/dwarfstack.qbs"

     CppApplication {
         property string heob_base_ver: "2.1-dev"
@@ -14,7 +14,7 @@ Project {
         }
         name: "heob"
         targetName: "heob" + (qbs.architecture === "x86_64" ? '64' : '32')
-        Depends { name: "dwarfstack" }
+//        Depends { name: "dwarfstack" }
         consoleApplication: true
         cpp.windowsApiCharacterSet: "mbcs"
         cpp.defines: "HEOB_VER=\"" + heob_ver + "\""

```

Then I get:

> compiling heob.c
> C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.11.25503/bin/HostX86/x64/cl.exe /nologo /c /EHsc /Od /Zi /MDd /Wall /D_MBCS /DWIN32 "/DHEOB_VER="\^""2.1-dev-2018-04-06"\^""" /FoC:\dev\heob-Desktop_Qt_5_9_4_MSVC2017_64bit-Debug\qtc_Desktop_Qt_5_9_4_MSVC2017_64bit_Debug\heob.83268501\3a52ce780950d4d9\heob-inj.c.obj C:\dev\heob\heob-inj.c /TC /FS -Wshadow -fno-omit-frame-pointer -fno-optimize-sibling-calls -ffreestanding
> cl : Command line error D8021 : invalid numeric argument '/Wshadow'

**Comment by ssbssa** [comment]
Here the same, the qbs can so far only be built with MinGW, I will try to add support for MSVC.
