### ISSUE TITLE
Issues building from command line

### ISSUE THREAD

**Issue by mitchcurtis** [ssbssa/heob#9]
I'm a scrub when it comes to building stuff like this, usually just relying on qmake to handle everything for me. My naive attempt to do a shadow build with [jom](https://wiki.qt.io/Jom) failed:

```
C:\dev>mkdir heob-build

C:\dev>cd heob-build

C:\dev\heob-build>jom CPPFLAGS="-DNO_DWARFSTACK" ..\heob\Makefile
Error: File Makefile doesn't exist.
```

nmake too:

```
C:\dev\heob-build>nmake CPPFLAGS="-DNO_DWARFSTACK" ..\heob\Makefile

Microsoft (R) Program Maintenance Utility Version 14.11.25507.1
Copyright (C) Microsoft Corporation.  All rights reserved.

..\heob\Makefile(2) : fatal error U1033: syntax error : '=' unexpected
Stop.
```

So I gave in and did an in-source build:

```
C:\dev>cd heob

C:\dev\heob>jom CPPFLAGS="-DNO_DWARFSTACK"
Error: syntax error in C:\dev\heob\Makefile line 8
```

It would be good to have some complete build instructions in the README. :)

**Comment by mitchcurtis** [comment]
Setting the environment variables should work, according to [this](https://msdn.microsoft.com/en-us/library/99at5bh3.aspx).

```
C:\dev\heob-build>set CPPFLAGS="-DNO_DWARFSTACK"

C:\dev\heob-build>echo %CPPFLAGS%
"-DNO_DWARFSTACK"
```

But when I run it:

```
C:\dev\heob-build>nmake ..\heob\Makefile

Microsoft (R) Program Maintenance Utility Version 14.11.25507.1
Copyright (C) Microsoft Corporation.  All rights reserved.

..\heob\Makefile(2) : fatal error U1033: syntax error : '=' unexpected
Stop.
```

**Comment by mitchcurtis** [comment]
I'm starting to come to the conclusion that this is not meant for building with MSVC, but MinGW. :)

**Comment by ssbssa** [comment]
Does that mean this issue can be closed, or do you need some more info?

**Comment by mitchcurtis** [comment]
Yep, go ahead. :)
